sudo: required
language: rust
os:
- osx
osx_image: xcode9.2
rust: stable
services:
- docker
env:
  global:
  - THERMITE_DEBUG_FILENAME: /tmp/thermite-debug.log
  matrix:
  - RBLANK_RUBY_VERSION: 2.3.5
  - RBLANK_RUBY_VERSION: 2.4.2
  - RBLANK_RUBY_VERSION: 2.5.0
matrix:
  include:
  - os: linux
    dist: trusty
    language: generic
    env: DOCKER_TAG=ruby2.3
  - os: linux
    dist: trusty
    language: generic
    env: DOCKER_TAG=ruby2.3-shared
  - os: linux
    dist: trusty
    language: generic
    env: DOCKER_TAG=ruby2.4
  - os: linux
    dist: trusty
    language: generic
    env: DOCKER_TAG=ruby2.4-shared
  - os: linux
    dist: trusty
    language: generic
    env: DOCKER_TAG=latest
  - os: linux
    dist: trusty
    language: generic
    env: DOCKER_TAG=latest-shared
  - os: osx
    osx_image: xcode9.3beta
    env: RBLANK_RUBY_VERSION=2.3.5
  - os: osx
    osx_image: xcode9.2
    env: RBLANK_RUBY_VERSION=2.3.5 RUBY_STATIC=1
  - os: osx
    osx_image: xcode9.3beta
    env: RBLANK_RUBY_VERSION=2.3.5 RUBY_STATIC=1
  - os: osx
    osx_image: xcode9.3beta
    env: RBLANK_RUBY_VERSION=2.4.2
  - os: osx
    osx_image: xcode9.2
    env: RBLANK_RUBY_VERSION=2.4.2 RUBY_STATIC=1
  - os: osx
    osx_image: xcode9.3beta
    env: RBLANK_RUBY_VERSION=2.4.2 RUBY_STATIC=1
  - os: osx
    osx_image: xcode9.3beta
    env: RBLANK_RUBY_VERSION=2.5.0
  - os: osx
    osx_image: xcode9.2
    env: RBLANK_RUBY_VERSION=2.5.0 RUBY_STATIC=1
  - os: osx
    osx_image: xcode9.3beta
    env: RBLANK_RUBY_VERSION=2.5.0 RUBY_STATIC=1

cache:
  cargo: true
  directories:
  - $TRAVIS_BUILD_DIR/vendor/bundle

before_install: test/ci/before_install.sh
script: test/ci/script.sh

deploy:
  provider: releases
  api_key:
    secure: GZFo4A2iPwQsT10C9Ge4CXHR/2z6/NPUODUuZr1FEgfCaqbrfk6r5l73JICBsuY1ZOgIxvy0sSCz6/npszwgZ022JacSqWuHjqJ9VbUQ6plmc+XY+pv6nAOFPCZ/MbmCMLD7pCUS0CvExzSIum0mh4iHhviBpz89MIQOlI9qt+rz2uqq0q6MbfImwQ0heywyYAdvn1/03odsV9/brbV8mDOszUboPPLJMok5IR/9kJfFd3aJkfMXWJQmnShwCsuTohS48JTE+Uwl2nXjAzgwwJQlRE/7YMQc9P4vS7iSm+uKRKepPz50sXiel9CsgzgYs5Gr8aqmp4n7oAHiXwTo7VrjI2uF6nynuTowChmT9pzX83+4NoKTsneW7kBZToVWvrpmzUfRZQsJLv2uVHh2cG6PWf+PhLFnrtiPPLA32Nq3e6P7moFVQy6rxHEMwLdj6iturBSY5qaaTOsoVT28TJMmvfMTka/Jg+JU1QLOzaWUn74wAOThzyvdT6yQ6gu74UK9Wa8JDYYMTlXqUWCaZp2r/4/fbyfVyRbNIAbq4zAKHD6uQxOub7UyHooZKh4YP91IDO0BTiJX5SJvSVqwXd69MsI1K5TxujuzJPmZWMmk/sm/KapwGqol6E2UMcrGxLviP42Ecxx58rjxfr3quD46zf3OmgVbBWxs0kDtKsk=
  file: rusty_blank-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    condition: ${TRAVIS_TAG} =~ '-rust'
    repo: malept/rusty_blank
    tags: true
