sudo: false
dist: trusty
language: rust
os:
- linux
- osx
dist: trusty
osx_image: xcode8
rust: stable
env:
  global:
  - THERMITE_DEBUG_FILENAME: /tmp/thermite-debug.log
  matrix:
  - RBLANK_RUBY_VERSION: 2.3.3
  - RBLANK_RUBY_VERSION: 2.4.0

cache:
  cargo: true
  directories:
  - $TRAVIS_BUILD_DIR/vendor/bundle
  - $HOME/.cache/pip

before_install:
- |
  rvm install "$RBLANK_RUBY_VERSION"
  rvm use "$RBLANK_RUBY_VERSION"
  ruby --version
  if [[ "$TRAVIS_OS_NAME" == "osx" ]] && ! which bundle > /dev/null; then
    gem install bundler
  fi
- bundle install --jobs=3 --retry=3 --path=$TRAVIS_BUILD_DIR/vendor/bundle

before_script:
- |
  export PATH=$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH
  if [[ "$TRAVIS_OS_NAME" == "osx" ]] && ! which pip > /dev/null; then
    wget https://bootstrap.pypa.io/get-pip.py
    python get-pip.py --user
  fi
  pip install 'travis-cargo<0.2' --user

script:
- travis-cargo build
- bundle exec rake test
- bundle exec rake thermite:tarball
- bundle exec rake install
- |
  if [[ -z "$TRAVIS_TAG" ]]; then
    gem uninstall rusty_blank
    CARGO=fake bundle exec rake install
  fi
- |
  if [[ -z "$TRAVIS_TAG" ]]; then
    gem uninstall rusty_blank
    gem install minitest
    CARGO=fake gem install pkg/*.gem
    ruby test/test_rusty_blank.rb
  fi
- if [[ -f "$THERMITE_DEBUG_FILENAME" ]]; then cat $THERMITE_DEBUG_FILENAME; fi

deploy:
  provider: releases
  api_key:
    secure: GZFo4A2iPwQsT10C9Ge4CXHR/2z6/NPUODUuZr1FEgfCaqbrfk6r5l73JICBsuY1ZOgIxvy0sSCz6/npszwgZ022JacSqWuHjqJ9VbUQ6plmc+XY+pv6nAOFPCZ/MbmCMLD7pCUS0CvExzSIum0mh4iHhviBpz89MIQOlI9qt+rz2uqq0q6MbfImwQ0heywyYAdvn1/03odsV9/brbV8mDOszUboPPLJMok5IR/9kJfFd3aJkfMXWJQmnShwCsuTohS48JTE+Uwl2nXjAzgwwJQlRE/7YMQc9P4vS7iSm+uKRKepPz50sXiel9CsgzgYs5Gr8aqmp4n7oAHiXwTo7VrjI2uF6nynuTowChmT9pzX83+4NoKTsneW7kBZToVWvrpmzUfRZQsJLv2uVHh2cG6PWf+PhLFnrtiPPLA32Nq3e6P7moFVQy6rxHEMwLdj6iturBSY5qaaTOsoVT28TJMmvfMTka/Jg+JU1QLOzaWUn74wAOThzyvdT6yQ6gu74UK9Wa8JDYYMTlXqUWCaZp2r/4/fbyfVyRbNIAbq4zAKHD6uQxOub7UyHooZKh4YP91IDO0BTiJX5SJvSVqwXd69MsI1K5TxujuzJPmZWMmk/sm/KapwGqol6E2UMcrGxLviP42Ecxx58rjxfr3quD46zf3OmgVbBWxs0kDtKsk=
  file: rusty_blank-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    condition: ${TRAVIS_TAG} =~ '-rust'
    repo: malept/rusty_blank
    tags: true
